# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base-aarch64:14.3.1"
  amd64: "ghcr.io/hassio-addons/base-amd64:14.3.1"
  armhf: "ghcr.io/hassio-addons/base-armhf:14.3.1"
  armv7: "ghcr.io/hassio-addons/base-armv7:14.3.1"
  i386: "ghcr.io/hassio-addons/base-i386:14.3.1"
labels:
  org.opencontainers.image.title: "FreeRadius Home Assistant Add-on"
  org.opencontainers.image.description: "FreeRadius for Home Assistant"
  org.opencontainers.image.source: "https://github.com/Jasperwolsing/FreeRadius-HA-addon"
  org.opencontainers.image.licenses: "MIT License"
