# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FreeRadius Home Assistant add-on
version: "1.2.0"
slug: FreeRadius
description: FreeRadius for Home Assistant
url: "https://github.com/Jasperwolsing/FreeRadius-HA-addon/tree/main"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
ports:
  1812/udp: 1812
  1813/udp: 1813
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
